title: indie-programming-language.github.io
theme: minima
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag
